apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/marom/wordpress
        env:
          - name: WORDPRESS_DB_HOST
            value: wordpress-db
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: WORDPRESS_DB_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: WORDPRESS_DB_PASSWORD
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: WORDPRESS_DB_NAME
          - name: WORDPRESS_CONFIG_EXTRA
            value: |
              define('WP_HOME','http://wordpress.local');
              define('WP_SITEURL','http://wordpress.local');
        ports:
          - containerPort: 80
        volumeMounts:
          - name: wp-data
            mountPath: /var/www/html
      volumes:
        - name: wp-data
          emptyDir: {}
