apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-db
spec:
  serviceName: "wordpress-db"
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-db
  template:
    metadata:
      labels:
        app: wordpress-db
    spec:
      containers:
      - name: mariadb
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/marom/mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: somewordpress
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: WORDPRESS_DB_NAME
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: WORDPRESS_DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: WORDPRESS_DB_PASSWORD
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
